### ISSUE TITLE
model?

### ISSUE THREAD

**Issue by yondu22** [Verssae/flask-tacotron2-tts-web-app#1]
which tacotron2 pretrained models can we use? can you show an example of using it

**Comment by Verssae** [comment]
Yeah, I added some descriptions to README. (my models are attached too)
Maybe you can install and execute this :)
And I recommend to try [NVIDIA/Tacotron2](https://github.com/nvidia/tacotron2)!

**Comment by yondu22** [comment]
Thanks, tensorflow and torch versions are missing in readme and requirements
also add this step
export PYTHONPATH="$PYTHONPATH:/path/to/flask-tacotron2-tts-web-app"
to avoid this error
```
ModuleNotFoundError: No module named 'tacotron2.layers'
```

**Comment by Verssae** [comment]
Thanks! I added tf and pytorch versions and example tts files. :)
